# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebbbf7cd086599fbd3b483d5bb4c0693618cdb5f3f5a576001ba4f105afe30e73a738f974f8876035a13b4f4f39a7c899eb7db62424c7ba0ca9e7943d0df5524

test:
  secret_key_base: 8103fe43c2d139b9dfbcd8df4f55162b3847da425215ca78e7bd2502baade25b2e7121c226d9bdb82a05c0f364850df821507dd8931c9de0b071b8e74d512100

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
